# Generated by Django 4.2.6 on 2023-11-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coding_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('problems', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50)),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('is_cgpa', models.BooleanField()),
                ('marks', models.FloatField()),
                ('school', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='home/images/education')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('desc', models.TextField()),
                ('image', models.ImageField(default='', upload_to='home/images/experience')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(default=None, max_length=30)),
                ('phone', models.BigIntegerField(blank=True, default=None)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('linkedin', models.URLField(blank=True, default=None)),
                ('instagram', models.URLField(blank=True, default=None)),
                ('twitter', models.URLField(blank=True, default=None)),
                ('dob', models.DateField(blank=True, default=None)),
                ('address', models.CharField(blank=True, default=None, max_length=50)),
                ('summary', models.TextField(blank=True, default=None)),
                ('bio', models.CharField(default=None, max_length=30)),
                ('image', models.ImageField(blank=True, default='', upload_to='home/images/profile')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('name', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('is_web', models.BooleanField(default=False)),
                ('is_ml', models.BooleanField(default=False)),
                ('desc', models.TextField(blank=True, default=None)),
                ('link', models.URLField(blank=True, default=None)),
                ('bio', models.CharField(default='Nothing', max_length=30)),
                ('image', models.ImageField(default='', upload_to='home/images/project')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Soft_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
                ('project_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.projects')),
            ],
            options={
                'unique_together': {('project_id', 'member_id')},
            },
        ),
    ]
